spring.application.name=church-backend
# SQLite Connection Settings
spring.datasource.url=jdbc:sqlite:church.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# System Admin Master Credentials
app.sysadmin.username=${SYS_ADMIN_USER:mjsysadmin}
app.sysadmin.password=${SYS_ADMIN_PASSWORD:MasterSecret2026!}